artifact_uri: file:c:/Users/marce/projetoPython/EEG/demencia/eeg-dementia-ml/mlruns-new/858064323093464703/5dd63a9a5f704bd48faa3ce73e0d07b8/artifacts
end_time: 1775135263063
entry_point_name: ''
experiment_id: '858064323093464703'
lifecycle_stage: active
run_id: 5dd63a9a5f704bd48faa3ce73e0d07b8
run_name: multiclass_final_20260402_1004
source_name: ''
source_type: 4
source_version: ''
start_time: 1775135246439
status: 3
tags: []
user_id: marce
