artifact_location: file:c:/Users/marce/projetoPython/EEG/demencia/eeg-dementia-ml/mlruns-new/858064323093464703
creation_time: 1775134466002
experiment_id: '858064323093464703'
last_update_time: 1775134466002
lifecycle_stage: active
name: eeg-dementia-classification
workspace: default
