artifact_uri: file:c:/Users/marce/projetoPython/EEG/demencia/eeg-dementia-ml/mlruns-new/858064323093464703/ac37de4cbd9149ef90fb2fbf5b4b137d/artifacts
end_time: 1775135245334
entry_point_name: ''
experiment_id: '858064323093464703'
lifecycle_stage: active
run_id: ac37de4cbd9149ef90fb2fbf5b4b137d
run_name: resampling_ADASYN_20260402_1004
source_name: ''
source_type: 4
source_version: ''
start_time: 1775135245248
status: 3
tags: []
user_id: marce
