artifact_uri: file:c:/Users/marce/projetoPython/EEG/demencia/eeg-dementia-ml/mlruns-new/858064323093464703/261cfaeee62a4a3fba4f745b660e2369/artifacts
end_time: 1775135246014
entry_point_name: ''
experiment_id: '858064323093464703'
lifecycle_stage: active
run_id: 261cfaeee62a4a3fba4f745b660e2369
run_name: resampling_Random_Undersampling_20260402_1004
source_name: ''
source_type: 4
source_version: ''
start_time: 1775135245827
status: 3
tags: []
user_id: marce
